### ISSUE TITLE
Logback JSON encoder.

### ISSUE THREAD

**Issue by sergiojoker11** [tomcat-slf4j-logback/tomcat9-slf4j-logback#19]
I find myself trying to add a json encoder (https://github.com/logstash/logstash-logback-encoder) to this package/jar and I have had very little success so far. 
Has anyone had better luck?

**Comment by hazendaz** [comment]
Please see https://github.com/tomcat-slf4j-logback/tomcat-slf4j-logback/issues/260

If something to add, I certainly can merge any provided PR as noted there at that time.  It sounded like the issue was likely resolved without additional support but always open to add support.

**Comment by sergiojoker11** [comment]
Yeap, I did see that thread and it sounded to me like a legit request still. Indeed, this tomcat-juli.jar can be unpacked and the logstash dependencies can be put back into a jar along with the original packages. That seem to imply some more work in comparison with downloading a single jar as you would if you are not interested in this logback encoder.
I understand that some projects don't demand this encoder, however, I don't think adding these few bits to it would make a big difference to the dependency size while some of us could benefit from it.
Happy to make the changes to the pom file if a version containing the change is published in a relative short period of time.

**Comment by sergiojoker11** [comment]
See https://github.com/tomcat-slf4j-logback/tomcat9-slf4j-logback/pull/20

**Comment by hazendaz** [comment]
merged into master.
